import { getContext, getModel, parseFilters } from "@/lib/data";
import type { SearchParams } from "@/lib/data";
import { RANGE_PRESETS } from "@/lib/analytics/context";
import { PRIORITY_TIERS, STALE_DAYS } from "@/lib/domain/model";
import { checkDataQuality } from "@/lib/domain/dataQuality";
import { isGeminiConfigured, GEMINI_MODEL } from "@/lib/ai/gemini/config";
import { Shell } from "@/components/layout/Shell";

export default async function AboutPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>;
}) {
  const sp = await searchParams;
  const filters = parseFilters(sp);
  const model = getModel();
  const ctx = getContext({ range: filters.range });
  const quality = checkDataQuality(model);

  const defs: { term: string; def: string }[] = [
    {
      term: "Data as of",
      def: `${model.asOfLabel}. All "days idle" and aging arithmetic counts back from this date, not from today — the dataset ends here.`,
    },
    {
      term: "Conversion",
      def: `Lead → delivery conversion is measured over matured cohorts only: leads at least ${model.maturityDays} days old (the observed median lead-to-delivery time). Leads younger than that are excluded and the count of excluded leads is always shown alongside the rate. A window with fewer than 10 matured leads reports "—" rather than 0%.`,
    },
    {
      term: "Revenue",
      def: "Recognised on delivery date, not order date or lead creation date — so a delayed delivery shifts revenue into a later month.",
    },
    {
      term: "Revenue at risk",
      def: `The deal value of open leads with no recorded activity for ${STALE_DAYS}+ days ("stale"). Lost and delivered leads are never counted. Open pipeline itself is present-tense and is not narrowed by the date range filter, so a stale lead is never hidden by picking a shorter window.`,
    },
    {
      term: "Priority score",
      def: "1–100, computed as deal value × idle time (log-scaled) × stage proximity to revenue × risk flags (overdue, weak branch, 30+ days idle), then normalised against the strongest case in the entire open book — not clamped, so the queue never has a saturated tie at the top.",
    },
    {
      term: "Status flags",
      def: "Branch, rep and stage anomalies come from a two-proportion z-test against the network baseline, not fixed thresholds. Critical at z ≤ −2.5, Watch at z ≤ −1.4, Healthy above +3 points of baseline.",
    },
    {
      term: "Target attainment",
      def: `Targets sum to more units than the network has ever delivered in a month, so attainment is shown with rank and the most recent month's pace — never as a standalone percentage that implies a fixable performance gap.`,
    },
    {
      term: "The AI layer",
      def: isGeminiConfigured()
        ? `Every number on screen comes from the rules-based analytics engine, never from the model. Ask DealerPulse and the Summarize buttons are backed by Gemini (${GEMINI_MODEL}) via server-only function calling: the model can only request one of a fixed set of read-only analytics tools, receives the already-computed result, and phrases the answer from that — it never invents a figure. If Gemini is unavailable or times out, the app falls back to the original deterministic Q&A engine so nothing breaks.`
        : "Every AI card — Executive Brief, branch/rep summaries, Why? explanations, recommendations, anomalies, and Ask DealerPulse — is generated by rules over already-computed analytics. Gemini is supported (see GEMINI_API_KEY in the server environment) but not configured in this deployment, so Ask DealerPulse currently runs on the deterministic rule-based Q&A engine: it answers only questions the router can map to a computed metric, and anything else returns \"I don't have enough data to answer that.\" rather than a guess.",
    },
  ];

  return (
    <Shell
      branches={model.branches}
      reps={model.reps.filter((r) => r.role === "sales_officer").map((r) => ({ id: r.id, name: r.name, branchId: r.branchId }))}
      asOfLabel={model.asOfLabel}
      scopeLabel="About"
      screenTitle="About"
      screenSubtitle="Data definitions and methodology"
      rangePresets={RANGE_PRESETS}
    >
      <div className="mx-auto flex max-w-[760px] flex-col gap-6">
        <p className="text-[13px] leading-[1.6] text-ink-secondary">
          DealerPulse is organised around DATA → INSIGHT → ACTION. Every screen answers what is
          happening, why, and what to do next. No chart exists unless it changes a decision. This
          page lets you check any claim the product makes.
        </p>

        <dl className="divide-y divide-line-row rounded-[10px] border border-line-hairline bg-bg-card">
          {defs.map((d) => (
            <div key={d.term} className="p-4">
              <dt className="text-[12.5px] font-semibold text-ink-primary">{d.term}</dt>
              <dd className="mt-1 text-[12.5px] leading-[1.6] text-ink-secondary">{d.def}</dd>
            </div>
          ))}
        </dl>

        <section className="rounded-[10px] border border-line-hairline bg-bg-card p-4">
          <h2 className="mb-2 text-[13.5px] font-semibold text-ink-primary">Architecture</h2>
          <pre className="overflow-x-auto whitespace-pre-wrap font-mono text-[11.5px] leading-[1.7] text-ink-tertiary">
{`dealership_data.json
  -> buildModel()          typed domain model, dates parsed, joins resolved
  -> analytics functions   funnel, aging, targets, reps, deliveries, trends, sources
  -> insight engine        anomaly detection (z-tests), priority scoring, recommendations
  -> AI presentation       executive brief, summaries, why-explanations, question router
  -> UI (this app)`}
          </pre>
        </section>

        <section className="rounded-[10px] border border-line-hairline bg-bg-card p-4 text-[12.5px] text-ink-secondary">
          <h2 className="mb-2 text-[13.5px] font-semibold text-ink-primary">Data quality</h2>
          {quality.severity === "clean" ? (
            <p>No data quality issues detected — every lead resolves to a known branch, rep and stage, has a customer name and a non-negative deal value, and no lead is dated after the data-as-of cutoff.</p>
          ) : (
            <>
              <p className="text-warning">
                {quality.issues.reduce((s, i) => s + i.count, 0)} record(s) flagged ({quality.severity}) — the AI layer is told about this and will not present affected figures as fully confident.
              </p>
              <ul className="mt-2 space-y-1">
                {quality.issues.map((i) => (
                  <li key={i.type} className="text-ink-muted">
                    {i.type}: {i.count} (e.g. {i.examples.join(", ")})
                  </li>
                ))}
              </ul>
            </>
          )}
        </section>

        <section className="rounded-[10px] border border-line-hairline bg-bg-card p-4 text-[12.5px] text-ink-secondary">
          <h2 className="mb-2 text-[13.5px] font-semibold text-ink-primary">Dataset scope</h2>
          <p>
            {model.branches.length} branches · {model.reps.length} reps · {model.leads.length} leads ·{" "}
            {model.deliveries.length} deliveries · {model.targets.length} monthly targets.
          </p>
          <p className="mt-1 text-ink-muted">
            Priority tiers: Critical ≥ {PRIORITY_TIERS.critical}, Needs Attention ≥{" "}
            {PRIORITY_TIERS.attention}, Watch below.
          </p>
          <p className="mt-1 text-ink-muted">
            Currently showing {ctx.range.label.toLowerCase()} · {ctx.cohort.length} leads in scope.
          </p>
        </section>
      </div>
    </Shell>
  );
}
